apiVersion: v1
kind: Secret
metadata:
  name: port-productivity-secrets
  namespace: port-productivity-mlops
type: Opaque
stringData:
  MLFLOW_TRACKING_URI: http://mlflow-server.mlflow.svc.cluster.local:5000
  DATABASE_URL: ""

